{{- range $serviceName, $service := .Values.services }}
{{- if and ($service.enabled | default true) ($service.s3Volumes) }}
{{- range $volName, $vol := $service.s3Volumes }}
{{- include "microservices.s3volume" (dict "parentName" $serviceName "volName" $volName "vol" $vol "namespace" ($service.namespace.name | default "default") "awsRegion" ($.Values.awsRegion | default "us-east-1") "root" $) }}
{{- end }}
{{- end }}
{{- end }}
