{{- range $serviceName, $service := .Values.services }}
{{- if and ($service.enabled | default true) ($service.serviceAccount) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceName }}-sa
  namespace: {{ $service.namespace.name | default "default" }}
  annotations:
    eks.amazonaws.com/role-arn: {{ tpl ($service.serviceAccount.roleArn | default (printf "arn:aws:iam::%s:role/%s-%s" $.Values.awsAccountNumber $.Values.environment ($service.serviceAccount.roleName | default ""))) $ }}
  labels:
    app: {{ $serviceName }}
    environment: {{ $.Values.environment }}
{{- end }}
{{- end }}
{{- range $jobName, $job := .Values.jobs }}
{{- if and ($job.enabled | default false) ($job.serviceAccount) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $jobName }}-sa
  namespace: {{ $job.namespace.name | default "default" }}
  annotations:
    eks.amazonaws.com/role-arn: {{ tpl $job.serviceAccount.roleArn $ }}
  labels:
    app: {{ $jobName }}
    environment: {{ $.Values.environment }}
{{- end }}
{{- end }}
